### ISSUE TITLE
iOS 16 HomeKit Issue

### ISSUE THREAD

**Issue by zawinglee** [lukasroegner/homebridge-dyson-pure-cool#263] opened 2022-06-28 16:55 UTC
I recently update to iOS 16 and I notice that something is malfunctioning. 

Everything will grey out when i open the setting page of the dyson.
![WechatIMG1](https://user-images.githubusercontent.com/22844289/176236420-8b8a2af9-2fd1-4c1e-81e6-30a52438ce9c.jpeg)
But I can still control the power and fan speed with toggles. 
![WechatIMG3](https://user-images.githubusercontent.com/22844289/176236415-e6bab4f3-0f90-4bf0-a24a-572c530af1cd.jpeg)

OUTCOME: all automation associated with the dyson mode will fail because iOS cannot fetch the state of the dyson. (For example, I have an automation setup on the sunrise that will turn off the dyson for me if the dyson is on).

HOWEVER, when i minimize the app and come back (switch to other app and come back), everything back to normal. 
![WechatIMG2](https://user-images.githubusercontent.com/22844289/176236417-c94d032e-2845-4a45-81ce-2c783a1936ce.jpeg)

Do you think I should report this issue to Apple because the iOS 16 is still on beta?

**Comment by hommegithub** [comment] 2022-07-01 20:04
I have the same issue

**Comment by codyc1515** [comment] 2022-07-09 04:01
Can confirm these fields are all greyed out for me on iOS 16 too. Do you have a HomeKit Certified air purifier to compare with? It may be an iOS 16 issue.

**Comment by zawinglee** [comment] 2022-07-09 20:33
> Can confirm these fields are all greyed out for me on iOS 16 too. Do you have a HomeKit Certified air purifier to compare with? It may be an iOS 16 issue.

me, negative.

**Comment by seank842** [comment] 2022-07-12 23:19
I can also confirm I'm have the same issue, most inputs are greyed out until I switch apps out of HomeKit and then back into it.

I'm running iOS 16 (20A5312j)

**Comment by johnypony3** [comment] 2022-07-23 11:56
Please dont add a me too comment, upvote the actual issue.

**Comment by johnypony3** [comment] 2022-07-23 12:00
I noticed automations that are set to `mode` and `auto` do not reflect on the fan itself.

**Comment by johnypony3** [comment] 2022-07-23 12:02
Duplicate of issue 262

**Comment by zawinglee** [comment] 2022-07-28 00:07
update: fixed on iOS 16 beta 4

**Closed** 2022-07-28 00:07 UTC
