### ISSUE TITLE
plugin generated a warning

### ISSUE THREAD

**Issue by jchhenderson** [lukasroegner/homebridge-dyson-pure-cool#172] opened 2021-03-19 17:45 UTC
Noticed this in my logs:
```
[3/19/2021, 8:43:05 AM] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[3/19/2021, 8:43:05 AM] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM10 Density': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
```

**Comment by CooperCGN** [comment] 2021-03-31 15:56
Same here

```
[31/03/2021, 17:49:47] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[31/03/2021, 17:49:47] [homebridge-dyson-pure-cool] This plugin generated a warning from the characteristic 'PM10 Density': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
```

**Comment by rchrch** [comment] 2021-04-05 20:11
I see the same warnings.  Only happens when the continuous monitoring service is switched off.  The warnings stop for me when enabling the continuous monitoring switch.  From a quick code glance, maybe simply checking for NaN around like 485 in dyson-pure-cool-device.js solves the problem.

Running Homebridge 1.3.2 and plugin version 1.8.7.

**Comment by lukasroegner** [comment] 2021-05-14 13:58
Duplicate of #164

**Closed by lukasroegner** 2021-05-14 13:58 UTC
