### ISSUE TITLE
Cache data from the sensors

### ISSUE THREAD

**Issue by Krocko** [lukasroegner/homebridge-dyson-pure-cool#18] opened 2019-09-12 18:08 UTC
Hi Lukas, me again.
Is it possible to cache the data from temperature, humidity and air quality?
If the device is off this sensor are showing `0`. 
I think it would be better to show the last measurement.
What do you think?

**Comment by Krocko** [comment] 2019-09-13 07:02
If the device is switched off and you restart homebridge (for any reason) the values from the sensors are shown as `0` .

**Comment by lukasroegner** [comment] 2019-09-13 07:04
Correct, the accessories are initialized with 0/Off/Inactive values.

**Comment by lukasroegner** [comment] 2019-09-13 07:05
However, even when the Dyson device is switched off, it reports environmental data and current state (in my case).

**Comment by Krocko** [comment] 2019-09-13 09:15
Yes. But for this you have to turn on "Kontinuierliche Überwachung". 
I don‘t want to do this.

**Comment by lukasroegner** [comment] 2019-09-13 09:18
And you also restart your Raspberry Pi automatically. I can understand the issue. Maybe I find time to implement it within the next weeks. Feel free to create a PR yourself.

**Comment by Krocko** [comment] 2019-09-13 09:21
I use homebridge on a synology with docker.

**Comment by luc-ass** [comment] 2019-09-13 21:06
Me too, nut does the last state actually reflect anything useful? For my home air quality changes quite rapidly. Is it of any use if the value is wrong? Apple also supports “not available”

**Comment by luc-ass** [comment] 2019-09-13 21:09
This: https://developer.apple.com/documentation/homekit/hmcharacteristicvalueairquality

Wouldn’t this be better?

**Comment by Krocko** [comment] 2019-09-14 05:54
Yes. And what about the humidity and temperature?

**Comment by lukasroegner** [comment] 2019-09-22 13:18
@Krocko Could you please check the debug logs and find out if the "0" values are reported by the devices (MQTT message "ENVIRONMENTAL-DATA")? Based on sample data provided by others I guess that the MQTT messages are still sent (despite having turned off "Kontinuierliche Überwachung") with "0" values.

**Comment by Krocko** [comment] 2019-09-22 16:03
How can I get the debug log?

**Comment by lukasroegner** [comment] 2019-09-23 07:27
You can start homebridge with the `-D` argument to get more logs than usual.

**Comment by Krocko** [comment] 2019-09-23 17:16
Is this what you need?

```
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"CURRENT-STATE","time":"2019-09-23T17:14
:05.000Z","mode-reason":"","state-reason":"MODE","dial":"OFF","rssi":"-37","product-state":{"fmod":"OFF","fnst":"OFF","fnsp":"0001","qta
r":"0004","oson":"OFF","rhtm":"OFF","filf":"3641","ercd":"02C0","nmod":"OFF","wacd":"NONE"},"scheduler":{"srsc":"edb8","dstv":"0001","tz
id":"0001"}}                                                                                                                            
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","tim
e":"2019-09-23T17:14:05.001Z","data":{"tact":"OFF","hact":"OFF","pact":"0003","vact":"0000","sltm":"OFF"}}                              
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"CURRENT-STATE","time":"2019-09-23T17:14
:05.002Z","mode-reason":"","state-reason":"MODE","dial":"OFF","rssi":"-38","product-state":{"fmod":"OFF","fnst":"OFF","fnsp":"0001","qta
r":"0004","oson":"OFF","rhtm":"OFF","filf":"3641","ercd":"02C0","nmod":"OFF","wacd":"NONE"},"scheduler":{"srsc":"edb8","dstv":"0001","tz
id":"0001"}}                                                                                                                            
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","tim
e":"2019-09-23T17:14:05.003Z","data":{"tact":"OFF","hact":"OFF","pact":"0003","vact":"0000","sltm":"OFF"}}                              
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"CURRENT-STATE","time":"2019-09-23T17:14
:05.004Z","mode-reason":"","state-reason":"MODE","dial":"OFF","rssi":"-37","product-state":{"fmod":"OFF","fnst":"OFF","fnsp":"0001","qta
r":"0004","oson":"OFF","rhtm":"OFF","filf":"3641","ercd":"02C0","nmod":"OFF","wacd":"NONE"},"scheduler":{"srsc":"edb8","dstv":"0001","tz
id":"0001"}}                                                                                                                            
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","tim
e":"2019-09-23T17:14:05.005Z","data":{"tact":"OFF","hact":"OFF","pact":"0003","vact":"0000","sltm":"OFF"}}                              
[9/23/2019, 7:13:46 PM] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","tim
e":"2019-09-23T17:14:05.006Z","data":{"tact":"OFF","hact":"OFF","pact":"0003","vact":"0000","sltm":"OFF"}}
```

**Comment by lukasroegner** [comment] 2019-09-24 07:07
Exactly, thank you so much. You can see that the `pact` value is still reported (i.e. air quality), however, the `tact` (i.e. temperature) and `hact` (i.e. humidity) are both reported as `OFF`.

I'll check if a temperature and humidity sensor can display "unknown".

**Comment by lukasroegner** [comment] 2019-09-24 11:45
@Krocko Please try the `development` branch. I added a check for the `OFF` values: if the provided value is `OFF`, the sensors are simply not updated (instead of being set to `0`).

**Comment by Krocko** [comment] 2019-09-24 16:36
Thank you very much Lukas!
This is working!

**Comment by lukasroegner** [comment] 2019-09-24 18:07
Merged into master (#19) and published on NPM (1.0.8).

**Comment by Krocko** [comment] 2019-09-24 18:50
Sorry Lukas.
After restarting Homebridge, the values are `0` again.

**Comment by lukasroegner** [comment] 2019-09-24 19:09
Sure, this fixes overwritten values while the the device is offline. If the device is offline when homebridge restarts, it is reset. This issue needs further improvements.

**Comment by lukasroegner** [comment] 2019-09-25 05:37
@Krocko Removed the initialization of all characteristics from the code, which still works for me (apparently, characteristics are created as soon as they are referenced for the first time).

You can test it on the `development` branch.

**Comment by Krocko** [comment] 2019-09-25 14:36
Installed it but still the same.

**Comment by lukasroegner** [comment] 2019-09-25 14:38
Have you switched your device on while the plugin was running? It should get a value for temperature and humidity (check that in the Home app). Then, switch the device off and restart homebridge.

Does this work?

**Comment by Krocko** [comment] 2019-09-25 14:42
Exactly.
But after the homebridge restart (and the device is switched off), i have `0`again.

**Comment by lukasroegner** [comment] 2019-09-25 14:44
For both temperature and humidity?

**Comment by Krocko** [comment] 2019-09-25 14:47
Yes.

**Comment by lukasroegner** [comment] 2019-09-25 14:49
Other properties (state of the device, night mode, air quality,...) are correct, though?

**Comment by Krocko** [comment] 2019-09-25 14:55
The device state is off (that is right) and the air quality is `unknown`

**Comment by lukasroegner** [comment] 2019-09-25 15:05
Before I dive deep into this issue, can you make sure that you have the latest version from the `development` branch installed? Setting the air quality to `UNKNOWN` is completely removed from the source code.

**Comment by Krocko** [comment] 2019-09-25 15:07
The version is showing 1.1.0

**Comment by lukasroegner** [comment] 2019-09-25 15:14
Ok, version is correct. First guess is that caching of sensor values is not implemented in homebridge. Have to take a look at the homebridge code, may take some time.

**Comment by Krocko** [comment] 2019-09-25 15:23
Deleted the CachedAccessories file and got the following error:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
fs.js:114
    throw err;
    ^
```

**Comment by Krocko** [comment] 2019-09-25 16:06
@lukasroegner with [this plugin](https://github.com/joe-ng/homebridge-dyson-link) it was working.
Maybe you find something helpful in the code?

**Comment by lukasroegner** [comment] 2019-09-25 16:11
Yes, the plugin explicitly caches the environment values. I really hoped it is not necessary to cache them at all, maybe this is the only way to fix the issue if "Kontinuierliche Überwachung" is disabled.

**Comment by Krocko** [comment] 2019-09-25 16:34
Maybe it is a chance to implement fakegato for the sensors. 😄

**Comment by lukasroegner** [comment] 2019-09-25 16:45
Feel free to submit a PR, would appreciate it.

**Comment by lukasroegner** [comment] 2019-09-26 07:17
@Krocko Added manual caching for sensors (temperature, humidity, air quality). Latest version in on the `development` branch.

**Comment by Krocko** [comment] 2019-09-26 14:00
Still the same.

**Comment by lukasroegner** [comment] 2019-10-01 09:32
@Krocko Updated the `development` branch. Now, debug logs are added each time values are written to the cache and read from the cache. You can start homebridge in debug mode and check whether the cache is filled properly.

**Comment by Krocko** [comment] 2019-10-01 15:52
Where are you writing this values?

**Comment by lukasroegner** [comment] 2019-10-01 15:56
Yes, should be in cached accessories, in the context of the air purifier accessory. If you restart homebridge, can you see the „Loading from cache“ log entries?

**Comment by Krocko** [comment] 2019-10-01 15:59
Seeing this:
`Cached accessories loaded.`

**Comment by Krocko** [comment] 2019-10-01 16:01
I think there is something wrong. No i got the following error again.
Are you writing with the wrong rights to this file?

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
fs.js:114
    throw err;
    ^
```

**Comment by lukasroegner** [comment] 2019-10-01 16:04
I‘m using the integrated method from homebridge to persist data, i.e. the context of accessories.

**Comment by Krocko** [comment] 2019-10-01 16:15
This is strange. I restored the backup of the accessories and persist folder i made before and homebridge is starting again.

**Comment by lukasroegner** [comment] 2019-10-01 16:17
I‘m on holidays and therefore cannot check it out with my devices, I‘ll test it on Friday.

**Comment by Krocko** [comment] 2019-10-01 16:20
Oh mate, please enjoy your holidays!
Sorry to bother you!

**Comment by lukasroegner** [comment] 2019-10-04 07:16
Did a test run on my debug environment. Works as expected. It seems that you have an issue with your installation.

First run (initial start of homebridge, devices are created):
`
[4.10.2019, 09:03:05] [DysonPureCoolPlatform] Cached accessories loaded.
[4.10.2019, 09:03:05] [DysonPureCoolPlatform] Signing in.
[4.10.2019, 09:03:06] [DysonPureCoolPlatform] Signed in.
[4.10.2019, 09:03:06] [DysonPureCoolPlatform] Adding new accessory with serial number XXX-XX-XXXXXXXX and kind AirPurifierAccessory.
[4.10.2019, 09:03:06] [DysonPureCoolPlatform] Adding new accessory with serial number XXX-XX-XXXXXXXX and kind SwitchAccessory.
[4.10.2019, 09:03:06] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT connection requested for XXX.XXX.XXX.XXX.
[4.10.2019, 09:03:06] [DysonPureCoolPlatform] Got devices from the Dyson API.
[4.10.2019, 09:03:07] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT connection established.
[4.10.2019, 09:03:07] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"CURRENT-STATE","time":"2019-10-04T07:03:35.000Z","mode-reason":"LAPP","state-reason":"MODE","dial":"OFF","rssi":"-52","channel":"4","fqhp":"47066","fghp":"62680","product-state":{"fpwr":"OFF","fdir":"ON","auto":"OFF","oscs":"OFF","oson":"ON","nmod":"OFF","rhtm":"ON","fnst":"OFF","ercd":"22IB","wacd":"NONE","nmdv":"0004","fnsp":"0004","bril":"0002","corf":"ON","cflr":"0083","hflr":"0083","sltm":"OFF","osal":"0149","osau":"0194","ancp":"CUST"},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}
[4.10.2019, 09:03:07] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2019-10-04T07:03:35.000Z","data":{"tact":"2937","hact":"0052","pm25":"0007","pm10":"0005","va10":"0004","noxl":"0001","p25r":"0008","p10r":"0008","sltm":"OFF"}}
[4.10.2019, 09:03:07] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Saving temperature to cache.
[4.10.2019, 09:03:07] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Saving humidity to cache.
[4.10.2019, 09:03:07] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Saving air quality to cache.
[4.10.2019, 09:04:00] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT connection ended.
[4.10.2019, 09:04:00] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT disconnected.
`

Second run (cached values are loaded):
`
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] Cached accessories loaded.
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] Signing in.
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] Signed in.
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for temperature: 20.69999999999999
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for humidity: 52
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for air quality: 1
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for air quality (PM 2.5): 7
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for air quality (PM 10): 5
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for air quality (VOC): 4
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Loading cached value for air quality (NO2): 1
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT connection requested for XXX.XXX.XXX.XXX.
[4.10.2019, 09:05:10] [DysonPureCoolPlatform] Got devices from the Dyson API.
[4.10.2019, 09:05:11] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT connection established.
[4.10.2019, 09:05:11] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"CURRENT-STATE","time":"2019-10-04T07:05:39.000Z","mode-reason":"LAPP","state-reason":"MODE","dial":"OFF","rssi":"-52","channel":"4","fqhp":"47066","fghp":"62680","product-state":{"fpwr":"OFF","fdir":"ON","auto":"OFF","oscs":"OFF","oson":"ON","nmod":"OFF","rhtm":"ON","fnst":"OFF","ercd":"22IB","wacd":"NONE","nmdv":"0004","fnsp":"0004","bril":"0002","corf":"ON","cflr":"0083","hflr":"0083","sltm":"OFF","osal":"0149","osau":"0194","ancp":"CUST"},"scheduler":{"srsc":"0000000000000000","dstv":"0000","tzid":"0001"}}
[4.10.2019, 09:05:11] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - MQTT message received: {"msg":"ENVIRONMENTAL-CURRENT-SENSOR-DATA","time":"2019-10-04T07:05:39.000Z","data":{"tact":"2937","hact":"0052","pm25":"0008","pm10":"0005","va10":"0004","noxl":"0001","p25r":"0009","p10r":"0008","sltm":"OFF"}}
[4.10.2019, 09:05:11] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Saving temperature to cache.
[4.10.2019, 09:05:11] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Saving humidity to cache.
[4.10.2019, 09:05:11] [DysonPureCoolPlatform] XXX-XX-XXXXXXXX - Saving air quality to cache.
`

I also removed the explicit caching that I implemented: works for me, as the latest values are always persisted in the `cachedAccessories` file for both, actuators and sensors. It seems that you have an issue with homebridge writing to the `cachedAccessories` file.

**Comment by lukasroegner** [comment] 2019-10-04 07:28
Removed the explicit caching, as homebridge already caches sensor values. Merged into master in #21 and new version 1.1.2 on NPM.

**Comment by Krocko** [comment] 2019-10-04 08:47
I use the [oznu/docker-homebridge](https://github.com/oznu/docker-homebridge).
Maybe @oznu can help with this error?

**Comment by Krocko** [comment] 2019-10-04 08:58
@lukasroegner can you please test the following:
1. disable "kontinuierliche Überwachung"
2. Turn on the Fan to get the data from the sensors
3. If the values are in the home App, turn off the Fan and unplug the power cord
4. restart homebridge

Have you now the cached values in the home app?

**Comment by lukasroegner** [comment] 2019-10-04 09:06
I checked the behavior by completely disabling the update mechanism (i.e. I commented out the processing of any messages coming from the devices) in another run of the latest version of the plugin.

I can see the following in the `cachedAccessories` as soon as the device has reported the temperature at least once:
```
{
    "displayName": "Current Temperature",
    "UUID": "...",
    "props": {
        "format": "float",
        "unit": "celsius",
        "minValue": -50,
        "maxValue": 100,
        "minStep": 0.1,
        "perms": [
            "pr",
            "ev"
        ]
    },
    "value": 20.8,
    "eventOnlyCharacteristic": false
}
```

When restarting homebridge (with updates commented out), the `value` is displayed in the Home app.

**Comment by Krocko** [comment] 2019-10-04 11:39
It is this commit: https://github.com/lukasroegner/homebridge-dyson-pure-cool/commit/fa75384208e794626ab5c575940cfb4aca9fa814

If i unplug the Fan, restore the persist folder and cachedaccessories folder i can restart the homebridge without error (as long the fan is unplugged).

If i revert the changes in this commit i can restart the homebridge without error even the fan is plugged in.

**Comment by lukasroegner** [comment] 2019-10-07 18:06
What is the difference between the old version (you can restart without unplugging the fan) and the new version (fails when fan is plugged into the power outlet): Temperature/humidity sensor is now only updated if the state is anything other than `OFF`. I cannot reproduce the behavior of homebridge crashing.

Suggestion: 
- Remove all devices from the array in the config. 
- Restart homebridge. Now, all devices should have been removed, including cached values that may be corrupt.
- Check in the Home app if all Dyson accessories are removed.
- Stop homebridge.
- Update to the latest version of the plugin.
- Add the devices back to the array in the config.
- Start homebridge.

**Comment by lukasroegner** [comment] 2019-10-08 06:42
Could you please check that again with CachedAccessories file closed while restarting homebridge?

**Comment by Krocko** [comment] 2019-10-08 07:08
I have done this already. But still the same.

**Comment by lukasroegner** [comment] 2019-10-13 08:22
I did two tests, one with a new and clean setup of homebridge on my Mac. The other one on my "live" environment on the Raspberry Pi.

1. Start homebridge
2. Wait for first MQTT message with sensor data
3. Unplug Dyson device
4. Restart homebridge

Result: Sensor data that has been reported with the MQTT message is still shown in the Home app => caching works.

Based on the data you reported on this issue, I strongly assume that your homebridge setup sometimes does not correctly write to the `CachedAccessories` file.

**Closed by lukasroegner** 2019-10-13 08:22 UTC
