### ISSUE TITLE
Invalid handling of emails with +

### ISSUE THREAD

**Issue by olek-p** [lukasroegner/homebridge-dyson-pure-cool#190] opened 2021-05-24 10:05 UTC
When entering my Dyson account email which contains the plus sign in the credentials generator, I receive an error message "Error while receiving 2FA challenge ID. Status Code: 400". (After removing the plus sign from the email address, I see the correct second step form.) 
I used to use that Dyson account in previous (pre-2.0) versions of the plugin which makes me think it's not an issue with the Dyson API but rather with the plugin.

Version 2.0.1

**Comment by lukasroegner** [comment] 2022-02-12 10:00
The credentials generator just takes the email address you put in and sends it to the Dyson API. As this is done via JSON (rather than query params or form data), I would not assume that a plus sign needs to be encoded in any way.

I know this issue is quite old, which is why I'm closing it for now. If the issue still persists, and you would be available for some testing, feel free to reopen it.

**Comment by akamensky** [comment] 2024-06-10 14:50
Same here, just base URL encoding of passed in data would fix it...

**Comment by lukasroegner** [comment] 2024-06-11 07:54
@akamensky Have you found a fix for the issue? If so, can you open a PR or post the respective code here?

**Comment by akamensky** [comment] 2024-06-12 02:43
@lukasroegner ive had an interesting conversation with their support. The summary is that the issue is on their side. I even cannot login to the app anymore. They accept registration with labelled email addresses, but no other requests will accept it after that. Moreover they are fully aware of this issue and the fact that their implementation is not compliant to relevant RFCs, but they will do nothing to fix it.

I think this needs to be added to the readme in h1 bold/red banner to say that the email used to register account should avoid using any "special characters".

**Closed** 2024-06-13 07:14 UTC
